# BASE UI -> Foreground Background buri
ColorColumn: '- background'
Conceal: ''  # IDK what these are bro
Cursor: 'background foreground'
CursorIM: '' # IDK what these are bro
CursorColumn: '- cursorLine'
CursorLine: '- cursorLine'
CursorLineNr: 'cursorColor cursorLine'
Directory: 'cyan1'
DiffAdd: 'green2 black2'        # TODO
DiffChange: 'cyan2 black2'      # TODO
DiffDelete: 'red2 black2'       # TODO
DiffText: 'foreground black2'   # TODO
EndOfBuffer: 'black1 background'
ErrorMsg: 'red1 background'
VertSplit: 'black1 vertSplit'
Folded: 'folded background'
FoldColumn: 'black1 background'
SignColumn: 'black1 background'
IncSearch: '' # TODO
LineNr: 'black1 background'
MatchParen: 'pureWhite matchParen'
ModeMsg: 'purple1'
MoreMsg: 'purple1'
NonText: '@EndOfBuffer'
Normal: 'foreground background'
PMenu: 'foreground pmenu'  # TODO
PMenuSel: 'magenta1 pureWhite' # TODO
PmenuSbar: '- pmenu'  # TODO h
PmenuThumb: 'foreground' # TODO
Question: 'purple1'
QuickFixLine: 'foreground quickFixLine'
Search: 'cursorColor search'
SpecialKey: 'yellow2 background'
SpellBad: 'red1 - u'
SpellLocal: 'foreground - u'
SpellCap: 'green1 - u'
SpellRare: 'yellow1 - u'
StatusLine: 'foreground background r'
StatusLineTerm: '@StatusLine'
StatusLineTermNC: 'vertSplit matchParen r'
StatusLineNC: '@StatusLineTermNC'
TabLine: 'darkness tabline'
TabLineFill: 'tabline darkness'
TabLineSel: 'tablineSel background'
Title: 'yellow2'
Visual: '- quickFixLine'
VisualNOS: '' #TODO
WarningMsg: 'yellow2 background'
WildMenu: 'darkness cursorColor'
diffAdded: 'purple1 -'
diffRemoved: 'red1 -'

# BASE SYNTAX
Comment: 'black1'
Constant: 'yellow1'
String: 'cyan1' # Constant
Character: '' # Constant
Boolean: '' # Constant
Number: '' # Constant
Float: '' # Constant
Identifier: 'foreground'
Function: 'green1' # Identifier
Statement: 'green1'
Conditional: '' # Statement
Repeat: '' # Statement
Label: '' # Statement
Operator: 'green1' # Statement
Keyword: '' # Statement
Exception: '' # Statement
PreProc: 'purple1'
Include: 'green1' # PreProc
Define: '' # PreProc
Macro: '' # PreProc
PreCondit: '' # PreProc
Type: 'green1'
StorageClass: 'green1' # Type
Structure: 'cyan1' # Type
Typedef: '' # Type
Special: 'purple1'
SpecialChar: '' # Special
Tag: '' # Special
Delimiter: 'foreground' # Special
SpecialComment: '' # Special
Debug: '' # Special
Underlined: 'green1 - u'
Ignore: ''
Error: '@ErrorMsg'
Todo: 'black2 yellow2 u'


# CSS
cssBraces: '@Delimiter'
cssClassName: '@Special'
cssClassNameDot: '@Normal'
cssPseudoClassId: '@Special'
cssTagName: '@Statement'

# CSS {VimPolyglot}
cssAttrComma: '@cssNoise'

# Hyper Help Text
helpHyperTextJump: '@Constant'

# HTML
htmlArg: '@Constant'
htmlEndTag: '@Statement'
htmlTag: '@Statement'
htmlTagName: 'green1'
htmlTagN: 'purple1'

# JSON
jsonQuote: '@Normal'

# PHP
phpVarSelector: '@Identifier'

# Python stuff {VimPolyglot}
pythonImport: 'magenta1'
pythonClassVar: 'cyan2'
pythonDot: '@Title'
pythonBuiltinType: '@pythonClassVar'
pythonFunction: 'green2'
pythonBuiltinFunc: 'purple1'
pythonRepeat: 'magenta1'
pythonOperator: 'purple2'


# Ruby
rubyDefine: '@Statement'
rubyFunction: '@Title'
rubyInterpolationDelimiter: '@String'
rubySharpBang: '@Comment'
rubyStringDelimiter: '@String'

# Shell script
sassClass: '@Special'

# Shell
shFunction: '@Normal'

#Vim Shit
vimContinue: '@Comment'
vimFuncSID: '@vimFunction'
vimFuncVar: '@Normal'
vimFunction: '@Title'
vimGroup: '@Statement'
vimHiGroup: '@Statement'
vimHiTerm: '@Identifier'
vimMapModKey: '@Special'
vimOption: '@Identifier'
vimVar: '@Normal'

# XML
xmlAttrib: '@Constant'
xmlAttribPunct: '@Statement'
xmlEndTag: '@Statement'
xmlNamespace: '@Statement'
xmlTag: '@Statement'
xmlTagName: '@Statement'

# Yaml and things
yamlKeyValueDelimiter: '@Delimiter'
CtrlPPrtCursor: '@Cursor'
CtrlPMatch: '@Title'
CtrlPMode2: '@StatusLine'

# Denite
deniteMatched: '@Normal'
deniteMatchedChar: '@Title'

# JSFlow?
jsFlowMaybe: '@Normal'
jsFlowObject: '@Normal'
jsFlowType: '@PreProc'

# GraphQL?
graphqlName: '@Normal'
graphqlOperator: '@Normal'

# GitMessage
gitmessengerHash: '@Comment'
gitmessengerHeader: '@Statement'
gitmessengerHistory: '@Constant'

# Javascript
jsArrowFunction: '@Operator'
jsBuiltins: 'magenta1'
jsLabel: 'purple2'
jsFuncBraces: ''
jsStatement: 'yellow2'
jsClassDefinition: '@Normal'
jsClassFuncName: '@Title'
jsDot: 'yellow1'
jsExport: '@Statement'
jsFuncName: 'purple1'
jsFunction: 'green2'
jsFutureKeys: '@Statement'
jsFuncCall: 'purple1'
jsGlobalObjects: '@Statement'
jsModuleKeywords: '@Statement'
jsModuleOperators: '@Statement'
jsNull: '@Constant'
jsObjectFuncName: '@Title'
jsObjectKey: '@Identifier'
jsObjectProp: 'magenta1'
jsOperator: 'foreground'
jsSuper: '@Statement'
jsTemplateBraces: '@Special'
jsUndefined: '@Constant'
jsStorageClass: 'purple2'

# Markdown
markdownBold: '@Special'
markdownCode: '@String'
markdownCodeDelimiter: '@String'
markdownHeadingDelimiter: '@Comment'
markdownRule: '@Comment'
ngxDirective: '@Statement'

# Plug
plug1: '@Normal'
plug2: '@Identifier'
plugDash: '@Comment'
plugMessage: '@Special'

# Signify
SignifySignAdd: '@GitGutterAdd'
SignifySignChange: '@GitGutterChange'
SignifySignChangeDelete: '@GitGutterChangeDelete'
SignifySignDelete: '@GitGutterDelete'
SignifySignDeleteFirstLine: '@SignifySignDelete'

# Startify
StartifyBracket: '@Comment'
StartifyFile: '@Identifier'
StartifyFooter: '@Constant'
StartifyHeader: '@Constant'
StartifyNumber: '@Special'
StartifyPath: '@Comment'
StartifySection: '@Statement'
StartifySlash: '@Comment'
StartifySpecial: '@Normal'

# Swift
swiftIdentifier: '@Normal'

# Typescript
typescriptAjaxMethods: '@Normal'
typescriptBraces: '@Normal'
typescriptEndColons: '@Normal'
typescriptFuncKeyword: '@Statement'
typescriptGlobalObjects: '@Statement'
typescriptHtmlElemProperties: '@Normal'
typescriptIdentifier: '@Statement'
typescriptMessage: '@Normal'
typescriptNull: '@Constant'
typescriptParens: '@Normal'

# PLUGINS
CtrlPMode1: 'darkness white1' 
EasyMotionShade: 'white1'
EasyMotionTarget: 'purple1'
EasyMotionTarget2First: 'yellow2'
EasyMotionTarget2Second: 'yellow2'
GitGutterAdd: 'purple1 background'
GitGutterChange: 'foreground background'
GitGutterChangeDelete: 'foreground background'
GitGutterDelete: 'red1 background'
gitmessengerEndOfBuffer: 'black1 darkness'
gitmessengerPopupNormal: 'foreground background'
Sneak: 'background yellow1'
SneakScope: 'green2 visualSel'
SyntasticErrorSign: 'red1 background'
SyntasticStyleErrorSign: '@SyntasticStyleErrorSign'
SyntasticStyleWarningSign: 'red2 background'
SyntasticWarningSign: '@SyntasticStyleWarningSign' 


# DART
dartSdkClass: 'green2'
dartInterpolation: 'magenta1'
dartFunction: 'purple1'
dartOperator: 'purple2'
dartRepeat: 'green1'
dartUserType: 'purple2'
dartTypeDef: 'yellow1'
dartCoreType: 'green2'
dartSpecialChar: 'yellow2'

# Java even though nobody would ever use this lolz
javaScopeDecl: 'purple1'
javaClassDecl: 'green2'
javaStorageClass: 'green1'
javaType: 'yellow2'
javaFold: 'cyan1'
javaConditional: 'purple1'
javaStatement: 'yellow2'
javaParenT: 'cyan1'
javaParen: ''
