# BASE UI -> Foreground Background buri (bold, underlined, reverse ,italic)
ColorColumn: '- background'
Conceal: ''  # IDK what these are bro
Cursor: 'background grey'
CursorIM: '' # IDK what these are either, bro
CursorColumn: '- cursorLine'
CursorLine: '- cursorLine'
CursorLineNr: 'grey2 cursorLine'
Directory: 'cyan'
DiffAdd: 'green2 darkPurp2'         # TODO
DiffChange: 'cyan darkPurp2'        # TODO
DiffDelete: 'red darkPurp2'         # TODO
DiffText: 'foreground darkPurp2'    # TODO
EndOfBuffer: 'darkPurp background'
ErrorMsg: 'red background'
VertSplit: 'pureBlack pureBlack'
Folded: 'darkPurp2 background'
FoldColumn: 'darkPurp background'
SignColumn: 'darkPurp background'
IncSearch: 'pureWhite visualSel'                       # TODO
LineNr: 'darkPurp background'
MatchParen: 'grey darkPurp'
ModeMsg: 'purple'
MoreMsg: 'purple'
NonText: '@EndOfBuffer'
Normal: 'foreground background'
PMenu: 'foreground darkPurp'        # TODO 
PMenuSel: 'yellow visualSel'        # TODO
PmenuSbar: 'foreground darkPurp2'   # TODO
PmenuThumb: 'foreground darkPurp2 ' # TODO
Question: 'purple'
QuickFixLine: 'foreground cursorLine'
Search: 'pureWhite search'
SpecialKey: 'orange background'
SpellBad: 'red - u'
SpellLocal: 'foreground - u'
SpellCap: 'green - u'
SpellRare: 'yellow - u'
StatusLine: 'foreground background r'
StatusLineTerm: '@StatusLine'
StatusLineTermNC: 'pureBlack darkPurp r'
StatusLineNC: '@StatusLineTermNC'
TabLine: 'pureBlack grey'
TabLineFill: 'grey pureBlack'
TabLineSel: 'grey2 background'
Title: 'orange'
Visual: 'foreground darkPurp2'
VisualNOS: '' #TODO
WarningMsg: 'orange background'
WildMenu: 'pureBlack grey2'
diffAdded: 'purple -'
diffRemoved: 'red -'

# BASE SYNTAX
Comment: 'comment'
Constant: 'yellow'
String: 'cyan'                      # Constant
Character: ''                       # Constant
Boolean: ''                         # Constant
Number: ''                          # Constant
Float: ''                           # Constant
Identifier: 'foreground'
Function: 'green'                   # Identifier
Statement: 'green'
Conditional: 'green2'               # Statement
Repeat: ''                          # Statement
Label: ''                           # Statement
Operator: 'orange'                   # Statement
Keyword: ''                         # Statement
Exception: ''                       # Statement
PreProc: 'purple'
Include: 'green'                    # PreProc
Define: ''                          # PreProc
Macro: ''                           # PreProc
PreCondit: ''                       # PreProc
Type: 'yellow'
StorageClass: 'green'               # Type
Structure: 'cyan'                   # Type
Typedef: 'cyan'                     # Type
Special: 'purple'
SpecialChar: 'red'                  # Special
Tag: ''                             # Special
Delimiter: 'foreground'             # Special
SpecialComment: ''                  # Special
Debug: ''                           # Special
Underlined: 'green - u'
Ignore: ''
Error: '@ErrorMsg'
Todo: 'pureWhite purple2 u'
